package rules

import (
	"fmt"
	"path/filepath"
	"strings"
)

// buildDocument renders the aggregated RULES.md: a version header, a context
// footprint, a provenance tally, a table of contents, and one section per rule.
func buildDocument(cfg Config, rs []rule) string {
	var b strings.Builder

	b.WriteString("# Rules\n\n")
	b.WriteString("<!-- Generated by `pk rules` from .claude/rules/. Do not edit; edit the source rules and regenerate. -->\n")
	if v := strings.TrimSpace(cfg.Version); v != "" {
		fmt.Fprintf(&b, "<!-- plankit %s -->\n", v)
	}
	b.WriteString("\n")

	// Fence the footprint so its column alignment survives markdown rendering.
	b.WriteString("```\n")
	writeFootprintLines(&b, cfg, rs)
	b.WriteString("```\n\n")

	managed, modified, local := tally(rs)
	fmt.Fprintf(&b, "Provenance: %d managed (pristine), %d modified, %d user-authored.\n", managed, modified, local)
	b.WriteString("Legend: [managed] pk-shipped & untouched · [modified] pk-shipped & edited · [local] user-authored.\n\n")

	b.WriteString("## Contents\n")
	for _, r := range rs {
		desc := r.description
		if desc == "" {
			desc = "(no description)"
		}
		fmt.Fprintf(&b, "- [%s](#%s): %s [%s] (kind: %s, ≈%s tokens)\n",
			r.title, slug(r.title), desc, provShort(r.provenance), r.kind, humanInt(r.tokens))
	}
	b.WriteString("\n")

	for _, r := range rs {
		b.WriteString("---\n\n")
		fmt.Fprintf(&b, "## %s\n", r.title)
		fmt.Fprintf(&b, "<!-- source: %s · %s · kind: %s -->\n\n", r.displayPath, provLong(r.provenance), r.kind)
		b.WriteString(stripH1(r.body))
		b.WriteString("\n")
	}

	return b.String()
}

// writeFootprint prints the always-on context summary to stderr. wrote controls
// the lead line: a confirmation when RULES.md was written, a dry-run notice when not.
func writeFootprint(cfg Config, rs []rule, wrote bool) {
	if wrote {
		fmt.Fprintln(cfg.Stderr, "Wrote RULES.md")
	} else {
		fmt.Fprintln(cfg.Stderr, "(dry-run) RULES.md not written")
	}
	var b strings.Builder
	writeFootprintLines(&b, cfg, rs)
	managed, modified, local := tally(rs)
	fmt.Fprintf(&b, "Provenance: %d managed (pristine), %d modified, %d user-authored.\n", managed, modified, local)
	fmt.Fprint(cfg.Stderr, b.String())
}

// writeFootprintLines writes the shared footprint block: a totals line followed by
// one aligned row per source (CLAUDE.md, when present, and the rules). The size and
// token columns are right-justified to a width computed from the values, so they
// line up in plain text without depending on a monospace renderer collapsing.
func writeFootprintLines(b *strings.Builder, cfg Config, rs []rule) {
	claudeBytes, claudeTokens, hasClaude := claudeStats(cfg)

	type row struct{ label, size, tokens string }
	var rows []row
	if hasClaude {
		rows = append(rows, row{"CLAUDE.md", formatBytes(claudeBytes), humanInt(claudeTokens)})
	}
	rows = append(rows, row{
		fmt.Sprintf(".claude/rules/ (%d files)", len(rs)),
		formatBytes(sumBytes(rs)),
		humanInt(sumTokens(rs)),
	})

	totalBytes := claudeBytes + sumBytes(rs)
	totalTokens := claudeTokens + sumTokens(rs)
	files := len(rs)
	if hasClaude {
		files++
	}
	fmt.Fprintf(b, "Always-on context: %d files, %s, %s tokens (estimated)\n",
		files, formatBytes(totalBytes), humanInt(totalTokens))

	labelW, sizeW, tokenW := 0, 0, 0
	for _, r := range rows {
		labelW = max(labelW, len(r.label))
		sizeW = max(sizeW, len(r.size))
		tokenW = max(tokenW, len(r.tokens))
	}
	for _, r := range rows {
		fmt.Fprintf(b, "  %-*s  %*s  %*s tokens\n", labelW, r.label, sizeW, r.size, tokenW, r.tokens)
	}
}

// claudeStats reports the size and token estimate of CLAUDE.md, which Claude Code
// also loads every session, so the footprint total is honest.
func claudeStats(cfg Config) (bytes, tokens int, exists bool) {
	data, err := cfg.ReadFile(filepath.Join(cfg.ProjectDir, "CLAUDE.md"))
	if err != nil {
		return 0, 0, false
	}
	content := normalizeLF(string(data))
	return len(content), estimateTokens(content), true
}

func tally(rs []rule) (managed, modified, local int) {
	for _, r := range rs {
		switch r.provenance {
		case "managed":
			managed++
		case "modified":
			modified++
		default:
			local++
		}
	}
	return
}

func sumBytes(rs []rule) int {
	var n int
	for _, r := range rs {
		n += r.bytes
	}
	return n
}

func sumTokens(rs []rule) int {
	var n int
	for _, r := range rs {
		n += r.tokens
	}
	return n
}

func provShort(p string) string {
	switch p {
	case "managed":
		return "managed"
	case "modified":
		return "modified"
	default:
		return "local"
	}
}

func provLong(p string) string {
	switch p {
	case "managed":
		return "plankit-managed (pristine)"
	case "modified":
		return "plankit-managed (modified)"
	default:
		return "user-authored"
	}
}

// stripH1 removes the first markdown H1 line from a body (the section already has
// its own "## Title" heading) and trims surrounding blank lines.
func stripH1(body string) string {
	lines := strings.Split(body, "\n")
	for i, line := range lines {
		if strings.HasPrefix(line, "# ") {
			lines = append(lines[:i], lines[i+1:]...)
			break
		}
	}
	return strings.TrimSpace(strings.Join(lines, "\n")) + "\n"
}

// slug converts a heading to a GitHub-style anchor.
func slug(title string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(title) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
		case r == ' ':
			b.WriteByte('-')
		}
	}
	return b.String()
}

// formatBytes renders a byte count as a compact, approximate size.
func formatBytes(n int) string {
	if n < 1024 {
		return fmt.Sprintf("%d B", n)
	}
	return fmt.Sprintf("~%d KB", (n+512)/1024)
}

// humanInt formats an integer with thousands separators (e.g. 5800 -> "5,800").
func humanInt(n int) string {
	s := fmt.Sprintf("%d", n)
	if len(s) <= 3 {
		return s
	}
	var b strings.Builder
	pre := len(s) % 3
	if pre > 0 {
		b.WriteString(s[:pre])
	}
	for i := pre; i < len(s); i += 3 {
		if b.Len() > 0 {
			b.WriteByte(',')
		}
		b.WriteString(s[i : i+3])
	}
	return b.String()
}
